name: Build deb package

on:
  push:
    branches: [ 6826-autostream ]

env:
  # Java version to use for the release
  RELEASE_JAVA_VERSION: 8
  BUILD_NUMBER: 6826-autostream

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install devscripts debhelper maven

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and test with Maven
        run: mvn verify -B -Pcoverage

      - name: Build Deb
        run: resources/build_deb_package.sh

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: debpkg
          path: '../*.deb'
